version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Viteホットリロード有効化
      - WATCHPACK_POLLING=true
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fastapi-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
