version: "3.9"



services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend

# top-level でボリューム定義
volumes:
  db_data: