FROM python:3.11

WORKDIR /fridge
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# PYTHONPATH を設定
ENV PYTHONPATH=/fridge

# FastAPIのホットリロード
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
# CMD ["sh", "-c", "python -m app.db.create_table && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]